name: 'retail_demand_forecasting'
version: '1.0.0'
config-version: 2

profile: 'retail_demand_forecasting'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  retail_demand_forecasting:
    staging:
      +materialized: view
      +schema: staging
      +database: RETAIL_DATA_WAREHOUSE
    intermediate:
      +materialized: view
      +schema: intermediate
      +database: RETAIL_DATA_WAREHOUSE
    marts:
      +materialized: table
      +schema: marts
      +database: RETAIL_DATA_WAREHOUSE
    ml:
      +materialized: view
      +schema: ml_features
      +database: RETAIL_DATA_WAREHOUSE
    metrics:
      +materialized: view
      +schema: metrics
      +database: RETAIL_DATA_WAREHOUSE