version: 2

models:
 - name: stg_census_retail_sales
   description: "Staged retail sales data from Census Bureau's Monthly Retail Trade Survey"
   columns:
     - name: month
       description: "Month in YYYY-MM format"
       tests:
         - not_null
     - name: state
       description: "Two-letter state code"
       tests:
         - not_null
     - name: category_445_sales
       description: "Sales value for Food and Beverage Stores (NAICS 445)"
       tests:
         - not_null
     - name: category_445_share
       description: "State's share of national sales for category 445"
       tests:
         - not_null
     - name: category_448_sales
       description: "Sales value for Clothing Stores (NAICS 448)"
       tests:
         - not_null
     - name: category_448_share
       description: "State's share of national sales for category 448"
       tests:
         - not_null

 - name: stg_weather_stats
   description: "Staged weather statistics from OpenWeather"
   columns:
     - name: state
       description: "Two-letter state code"
       tests:
         - not_null
     - name: month
       description: "Month number (1-12)"
       tests:
         - not_null
         - accepted_values:
             values: ['1','2','3','4','5','6','7','8','9','10','11','12']
     - name: mean_temp
       description: "Average temperature for the period"
       tests:
         - not_null
     - name: mean_precipitation
       description: "Average precipitation amount"
       tests:
         - not_null
     - name: temp_category
       description: "Temperature category"
       tests:
         - accepted_values:
             values: ['Cold', 'Mild', 'Hot']

 - name: int_retail_metrics
   description: "Intermediate retail metrics with calculated fields"
   columns:
     - name: month
       description: "Month in YYYY-MM format"
       tests:
         - not_null
     - name: state
       description: "Two-letter state code"
       tests:
         - not_null
     - name: category_445_sales
       tests:
         - not_null
     - name: category_448_sales
       tests:
         - not_null
     - name: mom_growth_445
       description: "Month-over-month growth for category 445"
     - name: mom_growth_448
       description: "Month-over-month growth for category 448"
     - name: seasonal_index_445
       description: "Seasonal index for category 445"
     - name: seasonal_index_448
       description: "Seasonal index for category 448"

 - name: mart_retail_analysis
   description: "Final mart combining retail metrics with economic and weather data"
   columns:
     - name: weather_month
       description: "Weather stats month number"
     - name: state
       description: "Two-letter state code"
       tests:
         - not_null
     - name: category_445_sales
       tests:
         - not_null
     - name: category_448_sales
       tests:
         - not_null

 - name: mart_inventory_planning
   description: "Inventory planning recommendations"
   columns:
     - name: month
       description: "Month in YYYY-MM format"
       tests:
         - not_null
     - name: state
       tests:
         - not_null
     - name: adjusted_safety_stock_445
     - name: adjusted_safety_stock_448
     - name: stock_recommendation_445
       tests:
         - accepted_values:
             values: ['Increase', 'Decrease', 'Maintain']
     - name: stock_recommendation_448
       tests:
         - accepted_values:
             values: ['Increase', 'Decrease', 'Maintain']

 - name: feature_engineering
   description: "ML features for demand forecasting"
   columns:
     - name: month
       description: "Month of the data point"
       tests:
         - not_null
     - name: state
       description: "Two-letter state code"
       tests:
         - not_null
     - name: target_445
       description: "Target variable for food & beverage sales"
       tests:
         - not_null
     - name: target_448
       description: "Target variable for clothing sales"
       tests:
         - not_null