version: 2

models:
  - name: stg_stock_prices
    description: "Staged stock price data"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: open
        description: "Opening price"
        tests:
          - not_null
      - name: high
        description: "Highest price"
        tests:
          - not_null
      - name: low
        description: "Lowest price"
        tests:
          - not_null
      - name: close
        description: "Closing price"
        tests:
          - not_null
      - name: volume
        description: "Trading volume"
        tests:
          - not_null

  - name: int_price_metrics
    description: "Intermediate price metrics including returns"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: price_change
        description: "Daily price change"
      - name: daily_return
        description: "Daily percentage return"
      - name: weekly_return
        description: "5-day percentage return"
      - name: price_gain
        description: "Positive price change"
      - name: price_loss
        description: "Absolute negative price change"

  - name: int_technical_indicators
    description: "Technical indicators calculations"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: ma_20
        description: "20-day simple moving average"
      - name: ma_50
        description: "50-day simple moving average"
      - name: rsi_14
        description: "14-day Relative Strength Index"
      - name: upper_band
        description: "Upper Bollinger Band (MA20 + 2σ)"
      - name: lower_band
        description: "Lower Bollinger Band (MA20 - 2σ)"

  - name: stock_analytics
    description: "Final stock analytics with technical indicators"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: open
        description: "Opening price"
        tests:
          - not_null
      - name: high
        description: "Highest price"
        tests:
          - not_null
      - name: low
        description: "Lowest price"
        tests:
          - not_null
      - name: close
        description: "Closing price"
        tests:
          - not_null
      - name: volume
        description: "Trading volume"
        tests:
          - not_null
      - name: daily_return
        description: "Daily percentage return"
      - name: weekly_return
        description: "5-day percentage return"
      - name: ma_20
        description: "20-day moving average"
      - name: ma_50
        description: "50-day moving average"
      - name: rsi_14
        description: "14-day Relative Strength Index"
      - name: upper_band
        description: "Upper Bollinger Band"
      - name: lower_band
        description: "Lower Bollinger Band"
      - name: trend_signal
        description: "Trend signal based on moving averages"
        tests:
          - accepted_values:
              values: ['BULLISH', 'BEARISH']
      - name: bollinger_signal
        description: "Signal based on Bollinger Bands"
        tests:
          - accepted_values:
              values: ['OVERBOUGHT', 'OVERSOLD', 'NEUTRAL']
      - name: rsi_signal
        description: "Signal based on RSI"
        tests:
          - accepted_values:
              values: ['OVERBOUGHT', 'OVERSOLD', 'NEUTRAL']