version: 2

sources:
  - name: raw_data
    database: RETAIL_DATA_WAREHOUSE
    schema: RAW_DATA
    tables:
      - name: retail_sales
        description: "Raw retail sales data from Census Bureau"
        columns:
          - name: month
            description: "Month of data (YYYY-MM)"
            tests:
              - not_null
          - name: state
            description: "Two-letter state code"
            tests:
              - not_null
          - name: category_445_sales
            description: "Sales for NAICS 445"
          - name: category_445_share
            description: "State's share of national sales for category 445"
          - name: category_448_sales
            description: "Sales for NAICS 448"
          - name: category_448_share
            description: "State's share of national sales for category 448"
          - name: national_445_total
            description: "National total sales for Food and Beverage Stores"
          - name: national_448_total
            description: "National total sales for Clothing Stores"
          - name: last_updated
            description: "Last update timestamp"
          - name: loaded_at
            description: "Data load timestamp"
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}

      - name: fred_economic_data
        description: "Raw economic indicators from FRED"
        columns:
          - name: month
            description: "Month in YYYY-MM format"
            tests:
              - not_null
          - name: consumer_confidence
            description: "Consumer confidence index"
          - name: unemployment_rate
            description: "Unemployment rate"
          - name: inflation_rate
            description: "Consumer Price Index changes"
          - name: gdp_growth_rate
            description: "Real GDP Growth Rate"
          - name: federal_funds_rate
            description: "Federal Funds Effective Rate"
          - name: retail_sales
            description: "Retail Sales Growth Rate"
          - name: last_updated
            description: "Last update timestamp"
          - name: loaded_at
            description: "Data load timestamp"
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}

      - name: weather_stats
        description: "Raw weather statistics"
        columns:
          - name: state
            description: "Two-letter state code"
            tests:
              - not_null
          - name: month
            description: "Month in MM format"
            tests:
              - not_null
          - name: mean_temp
            description: "Average temperature"
            tests:
              - not_null
          - name: mean_pressure
            description: "Average atmospheric pressure"
          - name: mean_humidity
            description: "Average relative humidity percentage"
          - name: mean_wind
            description: "Average wind speed"
          - name: mean_precipitation
            description: "Average precipitation amount"
          - name: mean_clouds
            description: "Average cloud coverage percentage"
          - name: sunshine_hours_total
            description: "Total hours of sunshine"
          - name: loaded_at
            description: "Data load timestamp"
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: business_performance
        description: "Business performance metrics"
        columns:
          - name: month
            description: "Month of data"
            tests:
              - not_null
          - name: state
            description: "State code"
            tests:
              - not_null
          - name: category_code
            description: "Retail category code (445 or 448)"
          - name: inventory_value
            description: "Value of inventory"
          - name: storage_cost
            description: "Cost of storage"
          - name: insurance_cost
            description: "Cost of insurance"
          - name: obsolescence_cost
            description: "Cost of obsolescence"
          - name: total_carrying_cost
            description: "Total inventory carrying cost"
          - name: stockout_events
            description: "Number of stockout events"
          - name: total_demand
            description: "Total demand"
          - name: lost_sales_value
            description: "Value of lost sales"
          - name: labor_hours_planned
            description: "Planned labor hours"
          - name: labor_hours_actual
            description: "Actual labor hours"
          - name: decision_request_time
            description: "Time of decision request"
          - name: decision_made_time
            description: "Time decision was made"
          - name: loaded_at
            description: "Data load timestamp"
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
