version: 2

sources:
  - name: raw
    database: dev
    schema: raw_data
    description: "Raw stock market data from Alpha Vantage API"
    tables:
      - name: alphavantage_stockprice
        identifier: alphavantage_stockprice
        description: "Raw daily stock price data"
        columns:
          - name: symbol
            description: "Stock ticker symbol"
            tests:
              - not_null
          - name: date
            description: "Trading date"
            tests:
              - not_null
          - name: open
            description: "Opening price"
          - name: high
            description: "Highest price during the day"
          - name: low
            description: "Lowest price during the day"
          - name: close
            description: "Closing price"
            tests:
              - not_null
          - name: volume
            description: "Trading volume"
        tests:
          - not_null:
              column_name: [symbol, date, close]

  - name: marts
    database: dev
    schema: marts
    description: "Transformed and analyzed stock market data"
    tables:
      - name: stock_analytics
        identifier: stock_analytics
        description: "Final analyzed stock data with technical indicators"